// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv @prisma/adapter-pg
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
